//! Crontab parsing (untrusted file content) and `cron.set` rendering.

use fleet_proto::op::CronEntry;
use fleet_proto::payload::CronLine;

/// First line of every crontab `cron.set` writes.
pub const HEADER: &str =
    "# Managed by Fleet (cron.set); local edits are replaced on the next change";

const MAX_FIELD: usize = 1024;

fn clip(s: &str) -> String {
    s.chars().take(MAX_FIELD).collect()
}

fn is_env_assignment(l: &str) -> bool {
    let Some((name, _)) = l.split_once('=') else {
        return false;
    };
    let name = name.trim();
    !name.is_empty()
        && !name.contains(char::is_whitespace)
        && name.bytes().all(|c| c.is_ascii_alphanumeric() || c == b'_')
        && !name.as_bytes()[0].is_ascii_digit()
}

/// Header lines `crontab` itself adds, and ours.
fn is_generated_comment(c: &str) -> bool {
    c.starts_with("DO NOT EDIT THIS FILE")
        || (c.starts_with('(') && (c.contains(" installed on ") || c.starts_with("(Cron version")))
        || c.starts_with("Managed by Fleet")
}

/// Parses a crontab. `system` files (`/etc/crontab`, `/etc/cron.d/*`) have a
/// user field after the schedule; it stays at the start of `command`. The
/// comment of an entry is the `#` line directly above it. Environment
/// assignments and malformed lines are skipped.
pub fn parse_crontab(text: &str, system: bool) -> Vec<CronLine> {
    let mut out = Vec::new();
    let mut comment: Option<String> = None;
    for raw in text.lines() {
        let l = raw.trim();
        if l.is_empty() {
            comment = None;
            continue;
        }
        if let Some(c) = l.strip_prefix('#') {
            let c = c.trim();
            comment = (!is_generated_comment(c) && !c.is_empty()).then(|| clip(c));
            continue;
        }
        if is_env_assignment(l) {
            comment = None;
            continue;
        }
        let parsed = if l.starts_with('@') {
            l.split_once(char::is_whitespace)
                .map(|(s, rest)| (s.to_owned(), rest.trim()))
        } else {
            let mut fields = l.split_whitespace();
            let sched: Vec<&str> = fields.by_ref().take(5).collect();
            // Rest of the line after the fifth field, spacing kept.
            let rest = nth_field_rest(l, 5);
            (sched.len() == 5).then(|| (sched.join(" "), rest.unwrap_or("")))
        };
        let Some((schedule, cmd)) = parsed else {
            comment = None;
            continue;
        };
        let min_fields = if system { 2 } else { 1 };
        if cmd.split_whitespace().count() < min_fields {
            comment = None;
            continue;
        }
        out.push(CronLine {
            schedule: clip(&schedule),
            command: clip(cmd),
            comment: comment.take(),
        });
    }
    out
}

/// Text after the first `n` whitespace-separated fields, trimmed.
fn nth_field_rest(l: &str, n: usize) -> Option<&str> {
    let mut rest = l.trim_start();
    for _ in 0..n {
        let end = rest.find(char::is_whitespace)?;
        rest = rest[end..].trim_start();
    }
    Some(rest.trim_end())
}

/// Crontab text for `cron.set`: our header, then per entry an optional
/// `# comment` line and `schedule command`. Arguments are validated
/// single-line values, so an entry can't spill into another line.
pub fn render(entries: &[CronEntry]) -> String {
    let mut s = format!("{HEADER}\n");
    for e in entries {
        if !e.comment.as_str().is_empty() {
            s.push_str(&format!("# {}\n", e.comment.as_str()));
        }
        s.push_str(&format!("{} {}\n", e.schedule.as_str(), e.command.as_str()));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use fleet_proto::args::{CronCommand, CronSpec, Label};

    #[test]
    fn user_crontab() {
        let t = "# DO NOT EDIT THIS FILE - edit the master and reinstall.\n\
                 # (/tmp/crontab.x installed on Mon Jan  1 00:00:00 2024)\n\
                 # (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)\n\
                 MAILTO=\"\"\nSHELL = /bin/bash\n\
                 # nightly backup\n0 3 * * *  /usr/local/bin/backup  --all\n\
                 \n*/5 * * * * echo a=b\n@reboot /usr/bin/true\n\
                 bad line\n1 2 3\n";
        let l = parse_crontab(t, false);
        assert_eq!(l.len(), 3);
        assert_eq!(l[0].schedule, "0 3 * * *");
        assert_eq!(l[0].command, "/usr/local/bin/backup  --all");
        assert_eq!(l[0].comment.as_deref(), Some("nightly backup"));
        assert_eq!(l[1].command, "echo a=b");
        assert_eq!(l[1].comment, None);
        assert_eq!(l[2].schedule, "@reboot");
    }

    #[test]
    fn system_crontab_needs_user_field() {
        let t = "17 * * * * root cd / && run-parts --report /etc/cron.hourly\n5 * * * * onlyuser\n";
        let l = parse_crontab(t, true);
        assert_eq!(l.len(), 1);
        assert!(l[0].command.starts_with("root cd /"));
    }

    #[test]
    fn render_roundtrips() {
        let e = vec![
            CronEntry {
                schedule: CronSpec::new("0 4 * * sun").unwrap(),
                command: CronCommand::new("/usr/bin/true").unwrap(),
                comment: Label::new("weekly").unwrap(),
            },
            CronEntry {
                schedule: CronSpec::new("*/5 * * * *").unwrap(),
                command: CronCommand::new("/bin/echo hi").unwrap(),
                comment: Label::new("").unwrap(),
            },
        ];
        let text = render(&e);
        assert_eq!(
            text,
            format!("{HEADER}\n# weekly\n0 4 * * sun /usr/bin/true\n*/5 * * * * /bin/echo hi\n")
        );
        let back = parse_crontab(&text, false);
        assert_eq!(back.len(), 2);
        assert_eq!(back[0].comment.as_deref(), Some("weekly"));
        assert_eq!(back[1].comment, None);
    }
}
