use super::*;
use crate::runner::{CommandOutput, FakeRunner};
use crate::testutil::{block, ctx, meta};
use fleet_proto::Tier;
use fleet_proto::args::{CronCommand, CronSpec, Label};

fn root() -> tempfile::TempDir {
    let d = tempfile::tempdir().unwrap();
    let p = d.path();
    for dir in ["etc/cron.d", "var/spool/cron/crontabs"] {
        std::fs::create_dir_all(p.join(dir)).unwrap();
    }
    std::fs::write(
        p.join("etc/passwd"),
        "root:x:0:0::/root:/bin/sh\nops:x:1000:1000::/home/ops:/bin/bash\n\
         web:x:1001:1001::/home/web:/bin/bash\n",
    )
    .unwrap();
    std::fs::write(
        p.join("etc/group"),
        "sudo:x:27:ops\nops:x:1000:\nweb:x:1001:\n",
    )
    .unwrap();
    std::fs::write(
        p.join("var/spool/cron/crontabs/web"),
        "# DO NOT EDIT THIS FILE - edit the master and reinstall.\n# job\n0 1 * * * /bin/job\n",
    )
    .unwrap();
    std::fs::write(p.join("var/spool/cron/crontabs/.x"), "* * * * * a\n").unwrap();
    std::fs::write(
        p.join("etc/crontab"),
        "SHELL=/bin/sh\n17 * * * * root run-parts x\n",
    )
    .unwrap();
    std::fs::write(
        p.join("etc/cron.d/php"),
        "09,39 * * * * root /usr/lib/php/clean\n",
    )
    .unwrap();
    std::fs::write(p.join("etc/cron.d/php.dpkg-old"), "* * * * * root old\n").unwrap();
    d
}

fn run(c: &SysCtx, op: Op, expected: Option<u64>) -> Result<Payload, ErrorCode> {
    let mut m = meta(op.clone(), Some(3));
    m.command.body.expected_version = expected;
    CronHandler.validate(c, &op, &m).map_err(|e| e.code())?;
    match block(CronHandler.handle(c, &op, &m)).map_err(|e| e.code())? {
        OpOutput::Payload(p) => Ok(p),
        OpOutput::Stream(_) => panic!(),
    }
}

fn entry(s: &str, c: &str, comment: &str) -> CronEntry {
    CronEntry {
        schedule: CronSpec::new(s).unwrap(),
        command: CronCommand::new(c).unwrap(),
        comment: Label::new(comment).unwrap(),
    }
}

#[test]
fn list_all_sources() {
    let d = root();
    let c = ctx(d.path(), Rc::new(FakeRunner::new()));
    let Payload::CronTabs(t) = run(&c, Op::CronList { user: None }, None).unwrap() else {
        panic!()
    };
    let sources: Vec<&str> = t.tabs.iter().map(|t| t.source.as_str()).collect();
    assert_eq!(
        sources,
        [
            "/var/spool/cron/crontabs/web",
            "/etc/crontab",
            "/etc/cron.d/php"
        ]
    );
    assert_eq!(t.tabs[0].user.as_deref(), Some("web"));
    assert_eq!(t.tabs[0].entries[0].comment.as_deref(), Some("job"));
    assert_eq!(t.tabs[1].entries[0].command, "root run-parts x");

    // A symlinked spool file is refused, not followed.
    std::os::unix::fs::symlink("/etc/shadow", d.path().join("var/spool/cron/crontabs/ops"))
        .unwrap();
    assert_eq!(
        run(
            &c,
            Op::CronList {
                user: Some(UserName::new("ops").unwrap())
            },
            None
        ),
        Err(ErrorCode::PolicyDenied)
    );
}

#[test]
fn set_writes_through_crontab_stdin() {
    let d = root();
    let entries = vec![entry("0 4 * * sun", "/usr/bin/true", "weekly")];
    let text = parse::render(&entries, "");
    let r = Rc::new(FakeRunner::new());
    r.expect(CRONTAB, &["-u", "web", "-"], Ok(CommandOutput::ok("")));
    let c = ctx(d.path(), r.clone());
    let current = user_tab(&c, "web").unwrap().version;
    let op = Op::CronSet {
        user: UserName::new("web").unwrap(),
        entries,
    };
    assert_eq!(
        run(&c, op.clone(), Some(current ^ 1)),
        Err(ErrorCode::VersionConflict { current })
    );
    assert!(r.calls().is_empty());
    run(&c, op, Some(current)).unwrap();
    let call = &r.calls()[0];
    assert_eq!(call.stdin.as_deref(), Some(text.as_bytes()));
    assert_eq!(call.program, "/usr/bin/crontab");
    assert_eq!(r.pending(), 0);

    let unknown = Op::CronSet {
        user: UserName::new("ghost").unwrap(),
        entries: vec![],
    };
    assert_eq!(run(&c, unknown, None), Err(ErrorCode::NotFound));
}

#[test]
fn set_refusals_and_env_kept() {
    let d = root();
    let p = d.path();
    std::fs::write(
        p.join("etc/passwd"),
        "root:x:0:0::/root:/bin/sh\nweb:x:1001:1001::/home/web:/bin/bash\n\
         fleet-gate:x:1100:1100::/:/bin/sh\nsshd:x:105:65534::/run/sshd:/bin/sh\n\
         toor:x:0:0::/:/bin/sh\nsvc:x:1002:1002::/:/usr/sbin/nologin\n\
         f:x:1003:1003::/:/bin/false\nbig:x:70000:70000::/:/bin/sh\n",
    )
    .unwrap();
    std::fs::write(p.join("etc/login.defs"), "UID_MIN 1000\nUID_MAX 60000\n").unwrap();
    let c = ctx(p, Rc::new(FakeRunner::new()));
    let op = |u: &str| Op::CronSet {
        user: UserName::new(u).unwrap(),
        entries: vec![],
    };
    for (u, want) in [
        ("fleet-gate", ErrorCode::PolicyDenied),
        ("sshd", ErrorCode::PolicyDenied), // system uid
        ("toor", ErrorCode::PolicyDenied), // uid 0 but not root
        ("big", ErrorCode::PolicyDenied),  // above UID_MAX
        ("svc", ErrorCode::PolicyDenied),  // nologin
        ("f", ErrorCode::PolicyDenied),    // /bin/false
        ("ghost", ErrorCode::NotFound),
    ] {
        assert_eq!(run(&c, op(u), Some(0)), Err(want), "{u}");
    }
    // Missing expected_version → conflict, crontab not run.
    let current = user_tab(&c, "web").unwrap().version;
    assert_eq!(
        run(&c, op("web"), None),
        Err(ErrorCode::VersionConflict { current })
    );

    // root is allowed (Elevated); env lines of the old crontab survive.
    std::fs::write(
        p.join("var/spool/cron/crontabs/root"),
        "MAILTO=ops\nPATH=/usr/bin:/bin\n0 1 * * * /old\n",
    )
    .unwrap();
    let r = Rc::new(FakeRunner::new());
    r.expect(CRONTAB, &["-u", "root", "-"], Ok(CommandOutput::ok("")));
    let c = ctx(p, r.clone());
    let current = user_tab(&c, "root").unwrap().version;
    run(&c, op("root"), Some(current)).unwrap();
    let stdin = r.calls()[0].stdin.clone().unwrap();
    assert_eq!(
        String::from_utf8(stdin).unwrap(),
        format!("{}\nMAILTO=ops\nPATH=/usr/bin:/bin\n", parse::HEADER)
    );
}

#[test]
fn set_escalation() {
    let d = root();
    let c = ctx(d.path(), Rc::new(FakeRunner::new()));
    let op = |u: &str| Op::CronSet {
        user: UserName::new(u).unwrap(),
        entries: vec![],
    };
    assert_eq!(op("root").tier(), Tier::Elevated);
    assert_eq!(op("ops").tier(), Tier::Change);
    let m = meta(op("ops"), Some(1));
    assert!(CronHandler.requires_elevated(&c, &op("ops"), &m).unwrap());
    assert!(!CronHandler.requires_elevated(&c, &op("web"), &m).unwrap());
}

#[test]
fn timers_json_and_fallback() {
    let d = root();
    let json = r#"[{"next":1700000000000000,"left":1,"last":0,"passed":null,"unit":"apt-daily.timer","activates":"apt-daily.service"},{"unit":"bad;name","next":1}]"#;
    let show = "Id=apt-daily.timer\nUnit=apt-daily.service\n\
                TimersCalendar={ OnCalendar=*-*-* 06,18:00:00 ; next_elapse=Tue 2024-01-02 06:00:00 UTC }\n\
                TimersMonotonic=\n";
    let r = Rc::new(FakeRunner::new());
    r.expect(
        timers::SYSTEMCTL,
        &["list-timers", "--all", "--no-pager", "--output=json"],
        Ok(CommandOutput::ok(json)),
    )
    .expect(
        timers::SYSTEMCTL,
        &[
            "show",
            "--no-pager",
            "--property=Id,Unit,TimersCalendar,TimersMonotonic",
            "--",
            "apt-daily.timer",
        ],
        Ok(CommandOutput::ok(show)),
    );
    let c = ctx(d.path(), r.clone());
    let Payload::Timers(t) = run(&c, Op::TimersList, None).unwrap() else {
        panic!()
    };
    assert_eq!(t.timers.len(), 1);
    assert_eq!(t.timers[0].next_ms, Some(1_700_000_000_000));
    assert_eq!(t.timers[0].last_ms, None);
    assert_eq!(t.timers[0].schedule, "OnCalendar=*-*-* 06,18:00:00");
    assert_eq!(t.timers[0].activates, "apt-daily.service");

    // systemd 249: no JSON → list-units names, times unknown.
    let r = Rc::new(FakeRunner::new());
    r.expect(
        timers::SYSTEMCTL,
        &["list-timers", "--all", "--no-pager", "--output=json"],
        Ok(CommandOutput::exit(1)),
    )
    .expect(
        timers::SYSTEMCTL,
        &[
            "list-units",
            "--type=timer",
            "--all",
            "--plain",
            "--no-legend",
            "--no-pager",
        ],
        Ok(CommandOutput::ok("fstrim.timer loaded active waiting Discard\n")),
    )
    .expect(
        timers::SYSTEMCTL,
        &[
            "show",
            "--no-pager",
            "--property=Id,Unit,TimersCalendar,TimersMonotonic",
            "--",
            "fstrim.timer",
        ],
        Ok(CommandOutput::ok(
            "Id=fstrim.timer\nUnit=fstrim.service\nTimersCalendar={ OnCalendar=weekly ; next_elapse=n/a }\n",
        )),
    );
    let c = ctx(d.path(), r.clone());
    let Payload::Timers(t) = run(&c, Op::TimersList, None).unwrap() else {
        panic!()
    };
    assert_eq!(t.timers[0].unit, "fstrim.timer");
    assert_eq!(t.timers[0].activates, "fstrim.service");
    assert_eq!(t.timers[0].schedule, "OnCalendar=weekly");
    assert_eq!(t.timers[0].next_ms, None);
    assert_eq!(r.pending(), 0);
}
