use crate::cloudinit::*;
use fleet_proto::args::{SshKeyAlgo, SshPublicKey, UserName};

fn ed25519(seed: u8, comment: &str) -> SshPublicKey {
    let mut blob = Vec::new();
    blob.extend(11u32.to_be_bytes());
    blob.extend(b"ssh-ed25519");
    blob.extend(32u32.to_be_bytes());
    blob.extend([seed; 32]);
    SshPublicKey::new(SshKeyAlgo::Ed25519, blob, comment.into()).unwrap()
}

const PRIVATE: &str = "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA\n-----END OPENSSH PRIVATE KEY-----\n";

fn input() -> CloudInit {
    CloudInit {
        admin: UserName::new("ops").unwrap(),
        authorized_keys: vec![
            ed25519(1, "fleet-device-mac1"),
            ed25519(2, "fleet-recovery"),
        ],
        host_keys: vec![HostKey {
            private_openssh: PRIVATE.into(),
            public: ed25519(3, "host"),
        }],
        hostname: Some("web-1".into()),
    }
}

const GOLDEN: &str = "#cloud-config
# Generated by Fleet (design §9.7). The Mac applies the full profile on first connection.
hostname: \"web-1\"
users:
  - name: \"ops\"
    groups: \"sudo\"
    shell: \"/bin/bash\"
    lock_passwd: true
    ssh_authorized_keys:
      - \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB fleet-device-mac1\"
      - \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC fleet-recovery\"
disable_root: true
ssh_pwauth: false
ssh_deletekeys: true
ssh_genkeytypes: []
ssh_keys:
  ed25519_private: \"-----BEGIN OPENSSH PRIVATE KEY-----\\nb3BlbnNzaC1rZXktdjEAAAAA\\n-----END OPENSSH PRIVATE KEY-----\\n\"
  ed25519_public: \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD host\"
write_files:
  - path: \"/etc/ssh/sshd_config.d/05-fleet-bootstrap.conf\"
    owner: \"root:root\"
    permissions: \"0644\"
    content: \"# Fleet bootstrap (design §9.7); replaced by the profile's 10-fleet.conf.\\nPermitRootLogin no\\nPasswordAuthentication no\\nKbdInteractiveAuthentication no\\n\"
";

#[test]
fn golden_output() {
    assert_eq!(render(&input()).unwrap(), GOLDEN);
}

#[test]
fn quoting_is_structure_safe() {
    assert_eq!(quote("a\"b\\c\nd"), "\"a\\\"b\\\\c\\nd\"");
    assert_eq!(quote("x\u{7f}\u{1b}y"), "\"x\\u007f\\u001by\"");
    assert_eq!(
        quote("key: value # not a comment"),
        "\"key: value # not a comment\""
    );
}

#[test]
fn rejects_bad_input() {
    let mut c = input();
    c.host_keys.clear();
    assert!(render(&c).is_err());
    let mut c = input();
    c.host_keys[0].private_openssh =
        "-----BEGIN OPENSSH PRIVATE KEY-----\nx\"\n-----END OPENSSH PRIVATE KEY-----\n".into();
    assert!(render(&c).is_err());
    let mut c = input();
    c.host_keys.push(c.host_keys[0].clone());
    assert!(render(&c).is_err());
    let mut c = input();
    c.hostname = Some("Web_1".into());
    assert!(render(&c).is_err());
    let mut c = input();
    c.admin = UserName::new("root").unwrap();
    assert!(render(&c).is_err());
    let mut c = input();
    c.authorized_keys.clear();
    assert!(render(&c).is_err());
}
