#!/usr/bin/env bash
# Stages the artifacts embedded in the app (agent packages, fleetctl) and
# generates apple/Fleet/Generated/BundledArtifacts.swift with what the
# signed executable pins about them:
#   agentPins       file name -> SHA-256 of each bundled .deb
#   fleetctlCDHash  cdhash (hex) of the ad-hoc signed embedded fleetctl
#
#   scripts/gen-bundled-artifacts.sh          # Xcode pre-build phase
#   scripts/gen-bundled-artifacts.sh --stub   # empty pins if the file is missing
#                                             # (so xcodegen picks the file up)
# FLEET_SKIP_AGENT_BUNDLE=1 leaves agentPins empty.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
gen="$root/apple/Fleet/Generated"
file="$gen/BundledArtifacts.swift"
mkdir -p "$gen"

write() { # write <pins-file|-> <cdhash>
    {
        echo "// Generated by scripts/gen-bundled-artifacts.sh. Do not edit."
        echo "enum BundledArtifacts {"
        echo "    static let agentPins: [String: String] = ["
        if [[ "$1" != "-" && -s "$1" ]]; then
            while read -r name sum; do
                [[ -n "$name" ]] && echo "        \"$name\": \"$sum\","
            done <"$1"
        else
            echo "        :"
        fi
        echo "    ]"
        echo "    static let fleetctlCDHash = \"$2\""
        echo "}"
    } >"$file.tmp"
    mv "$file.tmp" "$file"
}

if [[ "${1:-}" == "--stub" ]]; then
    [[ -f "$file" ]] || write - ""
    exit 0
fi

"$root/scripts/bundle-agent.sh" stage
"$root/scripts/build-fleetctl.sh" stage
write "$root/build/embed/agent-pins.txt" "$(cat "$root/build/embed/fleetctl.cdhash")"
